sudo: required
services:
  - xvfb
language: node_js

node_js:
   - node

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
   - npm install -g --silent @angular/cli

script:
   - npm run build
   - npm run lint

after_success:
   - npm run codacy
